# Generated by Django 5.2 on 2025-04-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_alter_score_high_score_alter_score_last_game_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
