# Generated by Django 5.2 on 2025-05-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lives',
            field=models.IntegerField(default=5, max_length=15),
        ),
    ]
