# Generated by Django 5.2 on 2025-05-13 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0008_user_lives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lives',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(15)]),
        ),
    ]
