# Generated by Django 5.2 on 2025-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0009_alter_user_lives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lives',
            field=models.IntegerField(),
        ),
    ]
