# Generated by Django 5.2 on 2025-05-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0010_alter_user_lives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(unique=True)),
                ('amount', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
