# Generated by Django 5.2 on 2025-05-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0011_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
