# Generated by Django 5.2 on 2025-05-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0012_alter_reward_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='mode',
            field=models.CharField(default='string'),
            preserve_default=False,
        ),
    ]
