# Generated by Django 5.2 on 2025-05-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0013_reward_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='investment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='amount',
            field=models.FloatField(),
        ),
    ]
