# Generated by Django 5.2 on 2025-05-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0014_user_investment_alter_reward_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='arcticFortuneLives',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pathToGloryLives',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
