# Generated by Django 5.2 on 2025-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0015_user_arcticfortunelives_user_pathtoglorylives'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('high_score', models.IntegerField()),
                ('last_game_score', models.IntegerField()),
                ('backup_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
